---
- hosts: localhost
  become: true
  connection: local
  vars:
    cacti_cron_schedule:
      minute: '*/5'
      hour: '*'
      day: '*'
      month: '*'
    cacti_db_info:
      host: '{{ cacti_db_host }}'
      port: '3306'
      db_name: '{{ cacti_db }}'
      user: '{{ cacti_db_user }}'
      password: '{{ cacti_db_password }}'
    cacti_site_dir: '{{ cacti_web_root }}/cacti'
    cacti_url_path: '/cacti/'
    cacti_user_info:
      name: '{{ cacti_user }}'
      password: '{{ cacti_user_password }}'
      comment: 'Cacti User Account'
    cacti_webserver_type: "apache2"
  roles:
  tasks:
    - name: setting fact Debian apache2
      set_fact:
        cacti_web_group: "www-data"
        cacti_web_owner: "www-data"
        cacti_web_root: "/var/www/html"
        cacti_webserver_handler: "apache2"
      when: >
            ansible_os_family == "Debian" and
            cacti_webserver_type == "apache2"

    - name: Creating Cacti User
      user:
        name: "{{ cacti_user_info.name }}"
        password: "{{ cacti_user_info.password }}"
        comment: "{{ cacti_user_info.comment|default(omit) }}"
        generate_ssh_key: yes

    - name: Configuring Cacti Settings
      template:
        src: "/config.php.j2"
        dest: "{{ cacti_site_dir }}/include/config.php"
        owner: "{{ cacti_web_owner }}"
        group: "{{ cacti_web_group }}"
        mode: 0644

    - name: Checking For MySQL Connection
      wait_for:
        port: 3306
        host: "{{ cacti_db_info.host }}"
        delay: 20
      changed_when: false

    - name: Checking If Cacti Schema Has Been Imported
      stat:
        path: "/config/.cacti_schema_imported"
      register: "cacti_schema_imported_check"

    - name: Importing Cacti Schema
      mysql_db:
        login_host: "{{ cacti_db_info.host }}"
        login_password: "{{ cacti_db_info.password }}"
        login_user: "{{ cacti_db_info.user }}"
        name: "{{ cacti_db_info.db_name }}"
        state: "import"
        target: "{{ cacti_site_dir }}/cacti.sql"
      register: "cacti_schema_imported"
      when: not cacti_schema_imported_check.stat.exists

    - name: Marking Cacti Schema As Imported
      file:
        path: "/config/.cacti_schema_imported"
        state: "touch"
      when: cacti_schema_imported.changed

    - name: Creating Cacti Poller Cron
      cron:
        name: "Cacti poller cron"
        user: "{{ cacti_user_info.name }}"
        minute: "{{ cacti_cron_schedule.minute }}"
        hour: "{{ cacti_cron_schedule.hour }}"
        day: "{{ cacti_cron_schedule.day }}"
        month: "{{ cacti_cron_schedule.month }}"
        job: "php {{ cacti_site_dir }}/poller.php 2>&1 >/dev/null"
        cron_file: "cacti_poller"

    - name: Configuring RRA/LOG Directory Permissions
      file:
        path: "{{ cacti_site_dir }}/{{ item }}"
        state: "directory"
        recurse: yes
        owner: "{{ cacti_user_info.name }}"
        group: "{{ cacti_web_group }}"
        mode: 0775
      with_items:
        - 'log'
        - 'rra'
